name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate Mochawesome report
      run: npm run test

    - name: Run tests and generate Mochawesome report
      run: npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v2

    - name: Report Coveralls (Linux)
      if: startsWith(runner.os, 'Linux')
      run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Report Coveralls (Windows)
      if: startsWith(runner.os, 'Windows')
      run: curl -sL https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.zip | zcat > ./coveralls.exe && ./coveralls.exe
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Report Coveralls (macOS)
      if: startsWith(runner.os, 'macOS')
      run: |
        brew tap coverallsapp/coveralls --quiet
        brew install coveralls --quiet
        coveralls