name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate Mochawesome report
      run: npm run test

    - name: Coveralls
      uses: coverallsapp/github-action@v2